<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See harness/README in the NetBeans platform -->
<!-- for some information on what you could do (e.g. targets to override). -->
<!-- If you delete this file and reopen the project it will be recreated. -->
<project name="org.opensim.javabrowser" default="netbeans" basedir=".">
    <description>Builds, tests, and runs the project org.opensim.javabrowser.</description>
    <target name="-pre-compile" if="is.windows">
        <echo message="Running pre-build tasks..."/>
        <get src="https://sourceforge.net/projects/myosin/files/opensim-gui/jxBrowser7/jxbrowser-win64-7.44.1.jar/download" 
         dest="release/modules/ext/jxbrowser-win64-7.44.1.jar" 
         usetimestamp="true" 
         verbose="true" />
    </target>
    <target name="-pre-compile" if="is.macos">
        <echo message="Running pre-build tasks..."/>
        <get src="https://sourceforge.net/projects/myosin/files/opensim-gui/jxBrowser7/jxbrowser-mac-arm-7.44.1.jar/download" 
         dest="release/modules/ext/jxbrowser-mac-arm-7.44.1.jar" 
         usetimestamp="true" 
         verbose="true" />
    </target>
    <import file="nbproject/build-impl.xml"/>
</project>
