/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.opensim.javabrowser.addBiomech;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import org.openide.util.Exceptions;
import org.opensim.*;
import org.opensim.modeling.Model;
import org.opensim.utils.ErrorDialog;
import org.opensim.view.motions.MotionsDB;
import org.opensim.view.pub.OpenSimDB;

/**
 *
 * @author ayman
 */
public class AddBiomechanicsHandleDownloadJPanel extends javax.swing.JPanel {
    String downloadPath;
    boolean downloadGenericModel = false;
    boolean downloadScaledModel = false;
    /**
     * Creates new form AddBiomechanicsHandleDownloadJPanel
     */
    public AddBiomechanicsHandleDownloadJPanel(String downloadFile) {
        initComponents();
        jTextField1.setText(downloadFile);
        this.downloadPath = downloadFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBoxUnscaledModel = new javax.swing.JCheckBox();
        jCheckBoxScaledModel = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jLabel1.text")); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setText(org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jTextField1.text")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxUnscaledModel, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jCheckBoxUnscaledModel.text")); // NOI18N
        jCheckBoxUnscaledModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUnscaledModelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxScaledModel, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jCheckBoxScaledModel.text")); // NOI18N
        jCheckBoxScaledModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxScaledModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxUnscaledModel)
                            .addComponent(jCheckBoxScaledModel))
                        .addGap(0, 199, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jCheckBoxUnscaledModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxScaledModel)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBoxUnscaledModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUnscaledModelActionPerformed
        // TODO add your handling code here:
        this.downloadGenericModel = jCheckBoxUnscaledModel.isSelected();
    }//GEN-LAST:event_jCheckBoxUnscaledModelActionPerformed

    private void jCheckBoxScaledModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxScaledModelActionPerformed
        // TODO add your handling code here:
        this.downloadScaledModel = jCheckBoxScaledModel.isSelected();
    }//GEN-LAST:event_jCheckBoxScaledModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxScaledModel;
    private javax.swing.JCheckBox jCheckBoxUnscaledModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void openModelsFromAddbiomechZip(String zipFilePath) {
        
        File testZip = new File(zipFilePath);
        if (!testZip.exists()){
            System.out.println("File "+zipFilePath+ " doesn't exist. Aborting.");
            return;
        }
        if (!zipFilePath.toLowerCase().endsWith(".zip")){
            System.out.println("File "+zipFilePath+ " is not a zip file. Aborting.");
            return;
        }
        System.out.println("Within openModelsFromAddbiomechZip: input file:"+zipFilePath);
        String parentPath = testZip.getParent();
        String destDir = parentPath+"/output/";
        //String targetFile = "config.txt"; // file to find

        File dir = new File(destDir);
        if (!dir.exists()) dir.mkdirs();
    
        try (ZipInputStream zis = new ZipInputStream(new FileInputStream(zipFilePath))) {
        ZipEntry entry;
        while ((entry = zis.getNextEntry()) != null) {
            
            String name = entry.getName();
            System.out.println("ZipEntry:"+name);
            File outFile = new File(destDir + name);

            if (entry.isDirectory()) {
                outFile.mkdirs();
            } else {
                // Ensure parent dirs exist
                outFile.getParentFile().mkdirs();

                // Write file to disk
                try (FileOutputStream fos = new FileOutputStream(outFile)) {
                    byte[] buffer = new byte[4096];
                    int len;
                    while ((len = zis.read(buffer)) > 0) {
                        fos.write(buffer, 0, len);
                    }
                }
                final String absolutePath = outFile.getAbsolutePath();

                // Check if this is the file we're looking for
                if (absolutePath.endsWith(".osim")){
                    System.out.println("Found file: " + absolutePath);
                    try {
                        if (downloadGenericModel && outFile.getName().contains("unscaled") ||
                                downloadScaledModel && !outFile.getName().contains("generic")){
                            Model aModel = new Model(absolutePath);
                            OpenSimDB.getInstance().addModel(aModel);
                            if (downloadScaledModel){
                                String ikFolder = outFile.getParentFile().getPath().concat("/../IK/");
                                Path folderPath = Paths.get(ikFolder);
                                try (DirectoryStream<Path> stream = Files.newDirectoryStream(folderPath, "*_ik.mot")) {
                                    for (Path dentry : stream) {
                                        MotionsDB.getInstance().loadMotionFile(dentry.toAbsolutePath().toString(), true);
                                    }
                                } catch (IOException e) {
                                    e.printStackTrace();
                                }
                            }
                        }
                    } catch (IOException ex) {
                        ErrorDialog.displayExceptionDialog(ex);
                    }
                }
                
            }

            zis.closeEntry();
        }

    }   catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }
}