/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.opensim.addBiomech;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.Queue;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import org.openide.util.Exceptions;
import org.opensim.modeling.Model;
import org.opensim.modeling.Storage;
import org.opensim.utils.ErrorDialog;
import org.opensim.view.ObjectSetCurrentEvent;
import org.opensim.view.motions.MotionEvent;
import org.opensim.view.motions.MotionsDB;
import org.opensim.view.pub.OpenSimDB;

/**
 *
 * @author ayman
 */
public final class AddBiomechanicsHandleDownloadJPanel extends javax.swing.JPanel implements Observer {

    String zipFilePath;
    List<String> modelsFound = new ArrayList<>();
    DefaultListModel<String> trialsModel = new DefaultListModel<>();
    List<AddBiomechanicsTrial> availableTrials = new ArrayList<>();
    Queue<Runnable> queue = new LinkedList<>();
    Storage ikMotion = null;
    Model aModel = null;
    private int trialLoadingStatus=0; // 1 model loaded, 2 motion loaded, 3 associated
    private String selectedModelPath = "";
    private int selectedTrialIndex = -1;
    private int userSelectedAction = 0; // 0 Open, 1 Open-associate 2 Open-not-associate
    /**
     * Creates new form AddBiomechanicsHandleDownloadJPanel
     */
    public AddBiomechanicsHandleDownloadJPanel(String downloadFile) {
        initComponents();
        jTextField1.setText(downloadFile);
        this.zipFilePath = downloadFile;
        jTrialsList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // fires once, not on every drag step
                selectedTrialIndex = jTrialsList.getSelectedIndex();
            }
        });
        processDownload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelActionButtonGroup = new javax.swing.ButtonGroup();
        jRadioButtonOpenModelNoAssoc = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jInfoPanel = new javax.swing.JPanel();
        jProgressScrollPane = new javax.swing.JScrollPane();
        jProgressTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jModelComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTrialsList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonOpenAssociate = new javax.swing.JRadioButton();
        jRadioButtonOpenModelOnly = new javax.swing.JRadioButton();

        modelActionButtonGroup.add(jRadioButtonOpenModelNoAssoc);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonOpenModelNoAssoc, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jRadioButtonOpenModelNoAssoc.text")); // NOI18N
        jRadioButtonOpenModelNoAssoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpenModelNoAssocActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jLabel1.text")); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setText(org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jTextField1.text")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jInfoPanel.border.title"))); // NOI18N

        jProgressScrollPane.setAutoscrolls(true);

        jProgressTextArea.setEditable(false);
        jProgressTextArea.setColumns(20);
        jProgressTextArea.setLineWrap(true);
        jProgressTextArea.setRows(5);
        jProgressTextArea.setWrapStyleWord(true);
        jProgressTextArea.setEnabled(false);
        jProgressScrollPane.setViewportView(jProgressTextArea);

        javax.swing.GroupLayout jInfoPanelLayout = new javax.swing.GroupLayout(jInfoPanel);
        jInfoPanel.setLayout(jInfoPanelLayout);
        jInfoPanelLayout.setHorizontalGroup(
            jInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jInfoPanelLayout.setVerticalGroup(
            jInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInfoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jPanel1.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jLabel3.text")); // NOI18N

        jTrialsList.setModel(trialsModel);
        jScrollPane2.setViewportView(jTrialsList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jModelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modelActionButtonGroup.add(jRadioButtonOpenAssociate);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonOpenAssociate, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jRadioButtonOpenAssociate.text")); // NOI18N
        jRadioButtonOpenAssociate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpenAssociateActionPerformed(evt);
            }
        });

        modelActionButtonGroup.add(jRadioButtonOpenModelOnly);
        jRadioButtonOpenModelOnly.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonOpenModelOnly, org.openide.util.NbBundle.getMessage(AddBiomechanicsHandleDownloadJPanel.class, "AddBiomechanicsHandleDownloadJPanel.jRadioButtonOpenModelOnly.text")); // NOI18N
        jRadioButtonOpenModelOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpenModelOnlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOpenAssociate)
                    .addComponent(jRadioButtonOpenModelOnly))
                .addGap(0, 159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButtonOpenModelOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpenAssociate)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addContainerGap())
                    .addComponent(jInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButtonOpenModelOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpenModelOnlyActionPerformed
        // TODO add your handling code here:
        setUserSelectedAction(0);
    }//GEN-LAST:event_jRadioButtonOpenModelOnlyActionPerformed

    private void jRadioButtonOpenAssociateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpenAssociateActionPerformed
        // TODO add your handling code here:
        setUserSelectedAction(1);
    }//GEN-LAST:event_jRadioButtonOpenAssociateActionPerformed

    private void jRadioButtonOpenModelNoAssocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpenModelNoAssocActionPerformed
        // TODO add your handling code here:
        setUserSelectedAction(2);
    }//GEN-LAST:event_jRadioButtonOpenModelNoAssocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jInfoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jModelComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jProgressScrollPane;
    private javax.swing.JTextArea jProgressTextArea;
    private javax.swing.JRadioButton jRadioButtonOpenAssociate;
    private javax.swing.JRadioButton jRadioButtonOpenModelNoAssoc;
    private javax.swing.JRadioButton jRadioButtonOpenModelOnly;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> jTrialsList;
    private javax.swing.ButtonGroup modelActionButtonGroup;
    // End of variables declaration//GEN-END:variables

    private void processDownload() {
        
        File testZip = new File(zipFilePath);
        if (!testZip.exists()){
            System.out.println("File "+zipFilePath+ " doesn't exist. Aborting.");
            return;
        }
        if (!zipFilePath.toLowerCase().endsWith(".zip")){
            System.out.println("File "+zipFilePath+ " is not a zip file. Aborting.");
            return;
        }
        String parentPath = testZip.getParent();
        String destDir = parentPath+"/output/";
        
        File dir = new File(destDir);
        if (!dir.exists()) dir.mkdirs();
        
        // For every trial we'll save 
        try (ZipInputStream zis = new ZipInputStream(new FileInputStream(zipFilePath))) {
        ZipEntry entry;
        while ((entry = zis.getNextEntry()) != null) {
            
            String name = entry.getName();
            File outFile = new File(destDir + name);

            if (entry.isDirectory()) {
                outFile.mkdirs();
            } else {
                // Ensure parent dirs exist
                outFile.getParentFile().mkdirs();

                // Write file to disk
                try (FileOutputStream fos = new FileOutputStream(outFile)) {
                    byte[] buffer = new byte[4096];
                    int len;
                    while ((len = zis.read(buffer)) > 0) {
                        fos.write(buffer, 0, len);
                    }
                }
                final String absolutePath = outFile.getAbsolutePath();

                // Check if this is the file we're looking for
                if (absolutePath.endsWith(".osim")){
                    System.out.println("Found file: " + absolutePath);
                    modelsFound.add(absolutePath);
                }
                if (absolutePath.endsWith(".trc")){
                    // Extract trial name and add to list
                    extractTrialNameAndSegmentFromTrc(absolutePath);
                }
            }
            zis.closeEntry();
        }
        filterModelsFound();
        jProgressTextArea.setText("Processing file:"+zipFilePath+"\n");
        jProgressTextArea.append("models found:"+modelsFound+"\n");
        jProgressTextArea.append("trials found:"+availableTrials+"\n");
        for (String item : modelsFound) {
            jModelComboBox.addItem(item);
        }
        for (AddBiomechanicsTrial item: availableTrials) {
            trialsModel.addElement(item.getName());
            jProgressTextArea.append(item.getDetails()+"\n");
        }
    }   catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }
    
    void extractTrialNameAndSegmentFromTrc(String fullTrcPath){
        Path path = Paths.get(fullTrcPath);
        String fullName = path.getFileName().toString();

        int dot = fullName.lastIndexOf('.');
        String name = dot > 0 ? fullName.substring(0, dot) : fullName;  // "file name without extension"
        // name typically on the form {trialName}_segment_{i}
        String trialName = name.split("_segment_")[0];
        String segmentNumber = name.split("_segment_")[1];
        AddBiomechanicsTrial testTrial = new AddBiomechanicsTrial(trialName);
        int index = availableTrials.indexOf(testTrial);
        if (index==-1){ // new trial
            AddBiomechanicsTrial newTrial = testTrial;
            availableTrials.add(newTrial);
            newTrial.addMarkerDataPath(path);
            newTrial.addSegment(segmentNumber);            
        }
        else { // add segment to existing trial
            AddBiomechanicsTrial existingTrial = availableTrials.get(index);
            existingTrial.addMarkerDataPath(path);
            existingTrial.addSegment(segmentNumber);
        }   
    }
    
    public void executeUserAction() {
        try {
            // Based on user selection, always will open selected model then handle availableTrials and data
            String absolutePath = (String) jModelComboBox.getSelectedItem();
            aModel = new Model(absolutePath);
            // Register as observer so that model and motion changes are triggered in turn not too early
            OpenSimDB.getInstance().addObserver(this);
            MotionsDB.getInstance().addObserver(this);
            trialLoadingStatus = 0;
            selectedModelPath = absolutePath;
            SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                    try {
                        OpenSimDB.getInstance().addModel(aModel);
                    } catch (IOException ex) {
                        ErrorDialog.displayExceptionDialog(ex);
                    }
            }});
            int[] indices = jTrialsList.getSelectedIndices();

            for (int i : indices) { // Single select
                selectedTrialIndex = i;
            }
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }

        
    }
    /**
     * @return the userSelectedAction
     */
    public int getUserSelectedAction() {
        return userSelectedAction;
    }

    /**
     * @param userSelectedAction the userSelectedAction to set
     */
    public void setUserSelectedAction(int userSelectedAction) {
        this.userSelectedAction = userSelectedAction;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (userSelectedAction==0){
           OpenSimDB.getInstance().deleteObserver(this);
           MotionsDB.getInstance().deleteObserver(this);
           return;
        }
        // When model set current is triggered trialLoadingStatus:0->1
        if (trialLoadingStatus==0 && arg instanceof ObjectSetCurrentEvent){
            trialLoadingStatus = 1;
            jProgressTextArea.append("Model successfully loaded\n");
            AddBiomechanicsTrial currentTrial = availableTrials.get(selectedTrialIndex);
            String ikStoFilename = currentTrial.getStitchedIK();
            SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                Storage ikStorage=null;
                try {
                    ikStorage = new Storage(ikStoFilename);
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
                if (ikStorage!=null)
                    MotionsDB.getInstance().loadMotionStorage(ikStorage, true, ikStoFilename);
            }});
        }
        if (trialLoadingStatus ==1 && arg instanceof MotionEvent &&
                ((MotionEvent)arg).getOperation() == MotionEvent.Operation.CurrentMotionsChanged){
            // Load marker data to associate with IK motion, do it on GUI thread so UI is not frozen and so that
            // changes propagate similar to GUI operation
            SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                AddBiomechanicsTrial currentTrial = availableTrials.get(selectedTrialIndex);
                String trcPath = currentTrial.getStitchedMarkerData();
                MotionsDB.getInstance().loadMotionFile(trcPath, false);
                //
                SwingUtilities.invokeLater(new Runnable(){
                    public void run() {              
                        AddBiomechanicsTrial currentTrial = availableTrials.get(selectedTrialIndex);
                        String grfPath = currentTrial.getStitchedGrf();
                        MotionsDB.getInstance().loadMotionFile(grfPath, false);
                        trialLoadingStatus = 2;
                    }
                    });
            }});
            
        }

    }
    // Filter down the long list of .osim files found, in particular:
    // models that end in _moco are removed as they have no use in the GUI
    //
    private void filterModelsFound() {
        modelsFound.removeIf(s -> s.endsWith("_moco.osim"));
        modelsFound.removeIf(s -> s.contains("ignore_physics"));
    }

}